### ISSUE TITLE
SSL connection problem

### ISSUE THREAD

**Issue by timeisflowing** [w-digital-scanner/w13scan#200]
Does not connect SSL any other site except only google, I think there's a problem with the lib/baseproxy  and option file..

**Comment by timeisflowing** [comment]
Chrome handshake error 

[7068:7079:1012/061030.370754:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -107

**Comment by boy-hack** [comment]
Do you trust the root certificate of w13scan?

**Comment by timeisflowing** [comment]
yes trusted root cert and allow all privileges..

**Comment by timeisflowing** [comment]
https://www.imageupload.net/image/s1.6T4qv
https://www.imageupload.net/image/s2.6TP2q

**Comment by boy-hack** [comment]
I am not quite sure about the specific reason, it may be the support library problem of ssl. I don't have these problems on my mac

**Comment by timeisflowing** [comment]
I solved the problem with my own certificate, I replaced it with the ones on certs road and reinstall full worked. Kindest regards
