### ISSUE TITLE
Python 意外退出

### ISSUE THREAD

**Issue by Southseast** [w-digital-scanner/w13scan#203]
在使用如下命令的时候。
```
w13scan -h
[1]    15342 abort      w13scan -h
```
![image](https://user-images.githubusercontent.com/34373144/69836526-6fdda080-1284-11ea-9ea4-c490e8ed5ad7.png)

**Comment by Southseast** [comment]
打扰了，我环境有问题。

**Comment by wangofjian** [comment]
我遇到了同样的问题，pip卸载了asn1crypto，重新安装后就可以了。
requirements.txt的版本是0.24.0，现在版本是1.4.0
