### ISSUE TITLE
ratio_true > self.UPPER_RATIO_BOUND - 1 这个判断疑问

### ISSUE THREAD

**Issue by GrootPank** [w-digital-scanner/w13scan#204]
if ratio_true > self.UPPER_RATIO_BOUND - 1 and (ratio_true - ratio_false) > self.DIFF_TOLERANCE:
            if ratio_false <= self.UPPER_RATIO_BOUND:
                is_inject = True
作者的这套系统值得我学习，在学习的过程中我发现在sqlbool 类型插件中的一个页面相似度判断存在疑问，ratio_true 的范围是0-1，而 self.UPPER_RATIO_BOUND - 1 是负数，所有这个比较好像是永远为true的。 还有 ratio_true - ratio_false 是不是应该用 abs绝对值。 我只懂代码，对安全不是很了解，所有请教作者，望作者有空解答一下我的疑惑，稍微指点下这个判断的作用，不胜感激。

**Comment by boy-hack** [comment]
应该是bug，感谢反馈
