### ISSUE TITLE
反馈三个问题

### ISSUE THREAD

**Issue by m82a3** [w-digital-scanner/w13scan#269]
# 反馈三个小问题
首先很敬佩师傅的作品，个人很喜欢这个工具。其次这边反馈三个小问题，因为本人的代码水平约等于无，可能没有办法给出问题出现的详细原因或者说直接辅助师傅做改进，所以三张图师傅就权当是事件型的小提醒吧。（第一次给别人提issue不太知道规范，你这边知晓了就好）

### 一、windows系统偶然出现“您的主机中的软件中止了一个已建立的连接”的情况
首先我的使用的环境是windows系统+burp+被动扫描插件，所以这个问题的话不见得完全是w13scan这边的问题，不过这里还是一并说一下。
![1](https://user-images.githubusercontent.com/21202283/78967714-c5f40780-7af2-11ea-92c7-21f548abccfc.jpg)

### 二、超大数据包的问题
首先需要吐槽的一点是，w13scan貌似是不支持导出html或者其他格式的report，这当中存在的一个问题就是，扫描结果的log我们只能在终端当中看到。要是平时的话也还好，不过在遇到像我下面图上这种场景（我记不太清是不是图片base64编码之后传输的数据包了）的时候，w13scan会把整个数据包打印出来，用不了几个包屏幕就被占满了，之前的结果也就都看不到了（可以>导向但是不喜欢）。其实这张图这个地方还出现了sql注入的误报情况，但是估计这原因就深了去了，一下被后面的结果刷上去了，我也没法采样发上来。
![超大数据包](https://user-images.githubusercontent.com/21202283/78968066-53cff280-7af3-11ea-80ec-ca1af0e6ee21.jpg)

### 三、敏感信息误报的问题
这个问题相对与其他漏洞来说相对还是比较普遍，我认为是不是可以考虑加一个“检测到大量命中但是返回包长度都相同就丢弃后面结果”的机制呢？
![敏感文件扫描误报](https://user-images.githubusercontent.com/21202283/78968327-bde89780-7af3-11ea-924f-e134719967c5.jpg)

以上

**Comment by boy-hack** [comment]
了解，新版快要发布了，敬请期待～

**Comment by boy-hack** [comment]
新版已发布
