### ISSUE TITLE
Releases on PyPI

### ISSUE THREAD

**Issue by fabaff** [w-digital-scanner/w13scan#285]
The latest release is not available on PyPI. There we have 0.9.17 while the GitHub release is at 2.0.2.

From a user's point of view is this a bit problematic as using `pip` for the installation is easier than checkout the repo, install the dependencies and start the tool directly.

**Comment by boy-hack** [comment]
no planNo plans at the moment.

**Comment by fabaff** [comment]
Hmm, then please remove the released version from PyPI and make a statement that you don't want contributions and that you are not going to release the tool in the most common way.

**Comment by boy-hack** [comment]
I looked at your github and it's probably your job to help people improve little things, but I'm sorry, that's not what I need!

**Comment by fabaff** [comment]
It's not my job but my responsibility as a packager that tools which we make available for the Fedora Package Collection follow certain standards to provide a proper user experience. There are policies in place which are forcing packagers to work with the upstream projects to solve issues (like the shebang). This is how Open source should work and there is prove that this approach is mutually beneficial.

Well, there are projects which have their own ideas/views and still think that working with git checkout is a smart and user friendly way to do it in 2020...I respect that.
