### ISSUE TITLE
结合crawlergo不需要这么麻烦吧？

### ISSUE THREAD

**Issue by Dawson0x00** [w-digital-scanner/w13scan#305]

**Comment by Dawson0x00** [comment]
结合crawlergo不需要这么麻烦吧？
直接在 crawlergo的launcher.py里面设置代理走w13设置的代理就行吧
就是https://github.com/timwhitez/crawlergo_x_XRAY里面的launcher.py里面设置

**Comment by boy-hack** [comment]
这样设计更好
