### ISSUE TITLE
lxml==4.5.0  lxml版本必须是4.5.0吗

### ISSUE THREAD

**Issue by cr1bug** [w-digital-scanner/w13scan#447]

**Comment by cr1bug** [comment]
在https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml 里我安装了 lxml-**4.5.2**-cp39-cp39-win_amd64.whl 但是pip install lxml==**4.5.0**仍然报错
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************

**Comment by cr1bug** [comment]
4.5.0死活装不上，4.5.2安装成功

**Comment by boy-hack** [comment]
lxml安装成功了就行，在requirement.txt删掉那一行继续 pip install -r requirements.txt

**Comment by cr1bug** [comment]
> lxml安装成功了就行，在requirement.txt删掉那一行继续 pip install -r requirements.txt

cryptography我安装最新版本成功，安装2.7报错如下：
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

**Comment by cr1bug** [comment]
> 4.5.0死活装不上，4.5.2安装成功

我知道了 在pypi.org 上下载对应的.whl文件
