### ISSUE TITLE
W13SCAN/scanners/PerServer/net_xss.py 插件问题请教

### ISSUE THREAD

**Issue by cr1bug** [w-digital-scanner/w13scan#456]
https://xxxx.com/(A(%22onerror=%22alert%601%60%22))/
类似的挖到几个 无法弹窗 src判无效漏洞，求教w8ay大哥

部分代码:
![image](https://user-images.githubusercontent.com/54324046/109629710-14811900-7b7f-11eb-84df-90bd9cdab4e6.png)

**Comment by boy-hack** [comment]
w13scan能探测漏洞，具体利用需要自己构造，学习下xss

**Comment by cr1bug** [comment]
已解决 参考https://xz.aliyun.com/t/7453
对于a href，请使用onmouseover或onclick代替onerror，否则无法使用
